wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.4
    cli_version: 0.17.7
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1723914094
    t:
      1:
      - 55
      - 95
      2:
      - 55
      - 95
      3:
      - 2
      - 23
      4: 3.12.4
      5: 0.17.7
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
